### ISSUE TITLE
Broken 3D Shepp-Logan phantom visualisation?

### ISSUE THREAD

**Issue by AaronGhost** [JuliaImageRecon/ImagePhantoms.jl#70]
Thanks for putting this library together!

I have been trying to obtain a 3D Shepp-Logan Phantom using the code provided in [3D Shepp-Logan Phantom](https://juliaimagerecon.github.io/ImagePhantoms.jl/stable/generated/examples/37-shepp3/). However it seems like the resulting image is fully null, similarly to the output on the page.

Could you please advise me how to produce meaningful 3D shepp logans?

**Comment by JeffFessler** [comment]
Whoops, I had not noticed that some recent change made the output null.  I will look into that right away and get back to you.  Thanks for telling me!

**Comment by JeffFessler** [comment]
Bug found - the fix is working its way through the CI process.  Fixed on main branch:
https://juliaimagerecon.github.io/ImagePhantoms.jl/dev/generated/examples/37-shepp3/
About to tag a new version.

**Comment by JeffFessler** [comment]
Fixed in 0.7.2:
https://juliaimagerecon.github.io/ImagePhantoms.jl/stable/generated/examples/37-shepp3/

Thanks for the feedback and let me know if you have any suggestions on how to make the package useful for you.
