### ISSUE TITLE
Is there a way to subtract 3d geometries

### ISSUE THREAD

**Issue by jakubMitura14** [JuliaImageRecon/ImagePhantoms.jl#86]
Hello a question rather then issue:  I would like to subtract a cylinder from bigger cylinder to get a hollow one - is there a way to subtract two geometries?

**Comment by JeffFessler** [comment]
You just need a negative value for the amplitude parameter.
The Shepp Logan phantoms do this:
https://github.com/JuliaImageRecon/ImagePhantoms.jl/blob/05f851ebac8c469a7991f89d2544f46f09d10470/src/shepplogan.jl#L163

Because overlapping objects are "added" by `phantom` etc.
